package io.alcatraz.ccd.coolapk.databeans.apk.detail

class Data {
    var id: Long = 0
    var apktype = 0
    var group_id = 0
    var catid = 0
    var yyb_app_id = 0
    var title: String? = null
    var subtitle: String? = null
    var version: String? = null
    var apkname: String? = null
    var apkname2: String? = null
    var apkmd5: String? = null
    var apk_beta_md5: String? = null
    var apk_alpha_md5: String? = null
    var apkversionname: String? = null
    var apkversioncode = 0
    var apk_sign_md5: String? = null
    var apk_sign_sha1: String? = null
    var apksize: String? = null
    var apklength: Long = 0
    var sdkversion = 0
    var maxsdkversion = 0
    var romversion: String? = null
    var ishp = 0
    var ishot = 0
    var isbiz = 0
    var iscps = 0
    var ispad = 0
    var isofficial = 0
    var is_coolapk_cpa = 0
    var recommend = 0
    var digest = 0
    var logo: String? = null
    var cover: String? = null
    var url: String? = null
    var open_link: String? = null
    var color: String? = null
    var shorttitle: String? = null
    var hotlabel: String? = null
    var shortlabel: String? = null
    var keywords: String? = null
    var description: String? = null
    var developeruid: Long = 0
    var developername: String? = null
    var developermail: String? = null
    var fromtype = 0
    var fromname: String? = null
    var fromid = 0
    var autoupdate = 0
    var star = 0
    var digg = 0
    var bury = 0
    var score: String? = null
    var votescore: String? = null
    var adminscore: String? = null
    var price = 0
    var click = 0
    var downnum = 0
    var follownum = 0
    var votenum = 0
    var favnum = 0
    var commentnum = 0
    var replynum = 0
    var albumnum = 0
    var comment_block_num = 0
    var share_feed_num = 0
    var viewnum = 0
    var hitnum = 0
    var hot_num = 0
    var creatoruid = 0
    var creatorname: String? = null
    var createdate: Long = 0
    var updateruid: Long = 0
    var updatername: String? = null
    var pubdate: Long = 0
    var lastupdate: Long = 0
    var rank_score: Long = 0
    var comment_status = 0
    var last_comment_update: Long = 0
    var is_forum_app = 0
    var allow_rating = 0
    var status = 0
    var entityType: String? = null
    var entityId: Long = 0
    var packageName: String? = null
    var shortTags: String? = null
    var apkTypeName: String? = null
    var apkTypeUrl: String? = null
    var apkUrl: String? = null
    var catDir: String? = null
    var catName: String? = null
    var downCount: String? = null
    var followCount: String? = null
    var voteCount: String? = null
    var commentCount: String? = null
    var replyCount: String? = null
    var updateFlag: String? = null
    var extraFlag: String? = null
    var apkRomVersion: String? = null
    var statusText: String? = null
    var pubStatusText: String? = null
    var commentStatusText: String? = null
    var target_id: String? = null
    var rating_star = 0.0
    var language: String? = null
    var tagList: List<String>? = null
    var thumbList: List<String>? = null
    var screenList: List<String>? = null
    var is_download_app = 0
    var apkfile: String? = null
    var votenum1 = 0
    var votenum2 = 0
    var votenum3 = 0
    var votenum4 = 0
    var votenum5 = 0
    var softtype: String? = null
    var remark: String? = null
    var goodwords: String? = null
    var badwords: String? = null
    var screenshots: String? = null
    var changehistory: String? = null
    var videourl: String? = null
    var developerurl: String? = null
    var introduce: String? = null
    var cpsurl: String? = null
    var cpslogurl: String? = null
    var ext_menu2_title: String? = null
    var ext_menu2_url: String? = null
    var ext_menu2_content: String? = null
    var ext_menu3_title: String? = null
    var ext_menu3_url: String? = null
    var ext_menu3_content: String? = null
    var offline_reason: String? = null
    var top_ids: List<String>? = null
    var recent_follow_list: List<Recent_follow_list>? = null
    var recommend_content: List<String>? = null
    var aid: Long = 0
    var realfile: String? = null
    var officialfile: String? = null
    var thirdfile: String? = null
    var permissions: List<String>? = null
    var changelog: String? = null
    var extendname: String? = null
    var extendfile: String? = null
    var file_exists = 0
    var voteLength: List<Int>? = null
    var votePercent: List<Int>? = null
    var reviewer: String? = null
    var apkKeywords: String? = null
    var apkDescription: String? = null
    var relatedRows: List<RelatedRows>? = null
    var developerRows: List<DeveloperRows>? = null
    var albumRows: List<AlbumRows>? = null
    var discoveryRows: List<String>? = null
    var followerRows: List<String>? = null
    var ratingRows: List<String>? = null
    var userAction: UserAction? = null
    var giftCount = 0
    var extendedMenus: List<ExtendedMenus>? = null
    var developerProfile: DeveloperProfile? = null
    var tabList: List<TabList>? = null
    var selectedTab: String? = null
}