package io.alcatraz.ccd.coolapk.databeans.user.space

class Data {
    var uid: Long = 0
    var username: String? = null
    var admintype = 0
    var groupid = 0
    var usergroupid = 0
    var level = 0
    var experience = 0
    var status = 0
    var block_status = 0
    var usernamestatus = 0
    var avatarstatus: Long = 0
    var avatar_cover_status: Long = 0
    var regdate: Long = 0
    var logintime: Long = 0
    var verify_title: String? = null
    var verify_status = 0
    var verify_developer = 0
    var verify_show_status = 0
    var user_type = 0
    var verify_show_type = 0
    var fetchType: String? = null
    var entityType: String? = null
    var entityId: Long = 0
    var displayUsername: String? = null
    var url: String? = null
    var userAvatar: String? = null
    var userSmallAvatar: String? = null
    var userBigAvatar: String? = null
    var cover: String? = null
    var next_level_experience = 0
    var next_level_percentage: String? = null
    var level_today_message: String? = null
    var level_detail_url: String? = null
    var groupName: String? = null
    var userGroupName: String? = null
    var verify_icon: String? = null
    var verify_label: String? = null
    var isDeveloper = 0
    var isFollow = 0
    var isBlackList = 0
    var isIgnoreList = 0
    var isLimitList = 0
    var isFans = 0
    var gender = 0
    var province: String? = null
    var city: String? = null
    var astro: String? = null
    var weibo: String? = null
    var blog: String? = null
    var bio: String? = null
    var apkDevNum = 0
    var feed = 0
    private var follow = 0
    private var fans = 0
    var apkFollowNum = 0
    var apkRatingNum = 0
    var apkCommentNum = 0
    var albumNum = 0
    var albumFavNum = 0
    var discoveryNum = 0
    var replyNum = 0
}