package io.alcatraz.ccd.coolapk.databeans.feed.detail

class Data {
    var id: Long = 0
    var type = 0
    var fid = 0
    var forwardid: String? = null
    var source_id: String? = null
    var uid: Long = 0
    var username: String? = null
    var dyh_id = 0
    var dyh_name: String? = null
    var ttype = 0
    var tcat = 0
    var tid = 0
    var ttitle: String? = null
    var tpic: String? = null
    var turl: String? = null
    var tinfo: String? = null
    var message_title: String? = null
    var message_title_md5: String? = null
    var message_keywords: String? = null
    var message_cover: String? = null
    var message: String? = null
    var pic: String? = null
    var message_length = 0
    var issummary = 0
    var istag = 0
    var is_html_article = 0
    var tags: String? = null
    var label: String? = null
    var user_tags: String? = null
    var media_type = 0
    var media_pic: String? = null
    var media_url: String? = null
    var extra_type = 0
    var extra_key: String? = null
    var extra_title: String? = null
    var extra_url: String? = null
    var extra_pic: String? = null
    var extra_info: String? = null
    var extra_status = 0
    var location: String? = null
    var fromid = 0
    var fromname: String? = null
    var likenum = 0
    var burynum = 0
    var commentnum = 0
    var replynum = 0
    var forwardnum = 0
    var reportnum = 0
    var relatednum = 0
    var favnum = 0
    var share_num = 0
    var comment_block_num = 0
    var question_answer_num = 0
    var question_follow_num = 0
    var hitnum = 0
    var viewnum = 0
    var feed_score = 0
    var rank_score: Long = 0
    var vote_score = 0
    var at_count = 0
    var url_count = 0
    var tag_count = 0
    var recommend = 0
    var is_anonymous = 0
    var is_hidden = 0
    var is_headline = 0
    var disallow_reply = 0
    var status = 0
    var message_status = 0
    var block_status = 0
    var dateline: Long = 0
    var lastupdate: Long = 0
    var device_title: String? = null
    var device_name: String? = null
    var device_rom: String? = null
    var device_build: String? = null
    var recent_reply_ids: String? = null
    var recent_hot_reply_ids: String? = null
    var recent_like_list: String? = null
    var related_dyh_ids: String? = null
    var post_signature: String? = null
    var message_signature: String? = null
    var fetchType: String? = null
    var entityId: Long = 0
    var avatarFetchType: String? = null
    var userAvatar: String? = null
    var entityTemplate: String? = null
    var entityType: String? = null
    var url: String? = null
    var feedType: String? = null
    var feedTypeName: String? = null
    var turlTarget: String? = null
    var info: String? = null
    var infoHtml: String? = null
    var title: String? = null
    var picArr: List<String>? = null
    var relateddata: List<String>? = null
    var media_info: String? = null
    var sourceFeed: String? = null
    var forwardSourceType: String? = null
    var shareUrl: String? = null
    var extra_fromApi: String? = null
    var disallow_repost = 0
    var long_location: String? = null
    var is_white_feed = 0
    var message_brief: String? = null
    var message_raw_output: String? = null
    var replyRows: List<String>? = null
    var replyRowsCount = 0
    var replyRowsMore = 0
    var userInfo: UserInfo? = null
    var relationRows: List<RelationRows>? = null
    var userAction: UserAction? = null
    var userLikeList: List<UserLikeList>? = null
    var hotReplyRows: List<HotReplyRows>? = null
    var detailSponsorCard: DetailSponsorCard? = null
}